name: Ubuntu 14.04 / Qt 5.12 for AppImage--
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildAppImage:
    runs-on: ubuntu-latest
    container:
      image: docker://subsurface/trusty-qt512:1.1

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: run build
      env:
         SUBSURFACE_REPO_PATH: ${{ github.workspace }}
      run: |
        cd ..
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}/libdivecomputer
        rm -rf /install-root/include/libdivecomputer
        bash -x subsurface/.github/workflows/scripts/linux-in-container-build.sh

    - name: prepare PR artifacts
      if: github.event_name == 'pull_request'
      run: |
        mkdir -p Linux-artifacts
        mv Subsurface.AppImage Linux-artifacts

    - name: PR artifacts
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: Linux-artifacts
        path: Linux-artifacts
