name: Mac
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  buildMac:
    runs-on: macOS-11
    steps:
    - name: checkout sources
      uses: actions/checkout@v1
    - name: setup Homebrew
      run: brew install autoconf automake libtool xz hidapi libusb libxml2 libxslt libzip openssl pkg-config libgit2 libssh2 libjpg libpng libmtp create-dmg
    - name: set our Qt build
      run: |
        curl --output ssrf-Qt-5.15.2-mac.tar.xz https://f002.backblazeb2.com/file/Subsurface-Travis/ssrf-Qt5.15.2.tar.xz
        tar -xJf ssrf-Qt-5.15.2-mac.tar.xz
    - name: build Subsurface
      run: |
        cd ${GITHUB_WORKSPACE}/..
        export QT_ROOT=${GITHUB_WORKSPACE}/Qt5.15.2/5.15.2/clang_64
        export QT_QPA_PLATFORM_PLUGIN_PATH=$QT_ROOT/plugins
        export PATH=$QT_ROOT/bin:$PATH
        export CMAKE_PREFIX_PATH=$QT_ROOT/lib/cmake
        DIR=$(pwd)

        # now build Subsurface with WebKit, using the generic build script
        bash -e -x ./subsurface/scripts/build.sh -desktop -build-with-webkit -release -build-deps -ftdi

        echo "finished initial build of Subsurface"

        # make sure we have FTDI enabled for the package
        cd subsurface/build
        FTDI=$(grep FTDISUPPORT:BOOL CMakeCache.txt | grep ON)
        if [ "$FTDI" != "FTDISUPPORT:BOOL=ON" ] ; then
          cmake -D FTDISUPPORT:BOOL=ON .
        fi
        echo "run the packaging script"
        bash -e -x ../packaging/macos/make-package.sh
        IMG=$(grep ^created: ../trigger-daily.log | tail -1 | cut -b10-)
        echo "Created $IMG"

    - name: test desktop build
      run: |
        # build export-html to make sure that didn't get broken
        cd ${GITHUB_WORKSPACE}/build
        make export-html
        echo "------------------------------------"
        echo "run tests for desktop build"
        export QT_ROOT=${GITHUB_WORKSPACE}/Qt/5.13.0/clang_64
        export QT_QPA_PLATFORM_PLUGIN_PATH=$QT_ROOT/plugins
        cd tests
        # ./TestGitStorage -v2
        make check

