name: Post Release
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  postRelease:
    runs-on: ubuntu-latest
    steps:
    - name: checkout sources
      uses: actions/checkout@v4

    # since we are running this step on a pull request, we will skip build numbers in releases
    - name: atomically create or retrieve the build number and assemble release notes
      id: version_number
      run: |
        bash -x ./scripts/get-atomic-buildnr.sh ${{ github.sha }} ${{ secrets.NIGHTLY_BUILDS }} "CICD-release"
        bash scripts/create-releasenotes.sh ${{ github.event.head_commit.id }}
        version=$(<release-version)
        echo "version=$version" >> $GITHUB_OUTPUT

    # ironically, we have to upload a file, otherwise this won't create a release with just the release notes
    - name: publish release
      if: github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version_number.outputs.version }}
        repository: subsurface/nightly-builds
        token: ${{ secrets.NIGHTLY_BUILDS }}
        prerelease: false
        files: gh_release_notes
        body_path: gh_release_notes
